nebulab/playbook

gli-uffici/musica.md

Update alla sezione Musica

---

crescita-personale/mentoring-e-1-1.md
gli-uffici/musica.md
lavorare-insieme/tool.md

L'occhio di falco sulle cose inutili...ma comunque andavano corrette 🦅

Microscopiche imperfezioni

---

README.md
lavorare-su-nebulab/blog.md
lavorare-su-nebulab/playbook.md
lavorare-su-nebulab/progetti-interni.md
lavorare-su-nebulab/sito-web.md

Lavorare su Nebulab

---

lavorare-insieme/firma-email.md

Add placeholder name and phone number

---

lavorare-insieme/dove-e-quando.md

Update max work hours info

---

crescita-personale/venerdi.md
lavorare-per-i-clienti/consuntivazione.md

Add Friday keepup policy

---

lavorare-insieme/tool.md

This closes #31 and closes #32.

Add Float and Appear.in tool section

---

lavorare-insieme/tool.md

Fix broken link

---

lavorare-insieme/salute-e-sicurezza.md

Aggiunge flexbot alla pagine salute e sicurezza

---

crescita-personale/venerdi.md

Riporta nuovi casi d'uso e principi che permettono a chi sta decidendo se lavorare o no su un cliente di Venerdì di scegliere in maniera più autonoma.

Modifica dei Venerdì sui clienti

---

lavorare-insieme/ferie-permessi-malattia.md

- Add lost hours rule
- Update the number of yearly vacation days from 26 to 22 (due to administrative changes)
- Changes the vacation hours report flow due to some changes in the Float UI
- Copy fixes

Add lost hours rule and minor updates

---

README.md

It can be useful to list all our wallpapers in some places so it's easy for everyone to get them.

Add link to press kit

---

gli-uffici/musica.md

Make a PR on GitHub & get a free T-Shirt!

Add Rap and Trap from the banned music genres

---

README.md
come-lavoriamo/consuntivazione.md
come-lavoriamo/tool.md
procedure/ferie-permessi-malattia.md

Closes #73, #74 and #75.
After a testing period, we're ready to introduce our brand new time management workflow.
We'll use Harvest for tracking both billable and non-billable projects hours and DiC for office attendance.
Introduces also Zoom.us, it's not ready for clients meeting though.

New time management flow

---

sviluppo/guida-stilistica.md

Write FE style guide

---

crescita-personale/benefit.md

Apply corrections to Benefits

---

sviluppo/usare-git-e-github.md

Update branch naming conventions

---

.github/pull_request_template.md

Using a checkbox makes it easier to catch missed updates and engages more the author. Also removed the title "Description" as it was redundant.
- Does this change need a public announcement? If yes, please update [the agenda of our monthly meeting](https://docs.google.com/document/d/1hjSS-o_cKs5Db1E1TqRykfQfnAQUFS4gDXMQ2x-CSzE/edit?usp=sharing).

Make the PR template more assertive

---

development/style-guide.md

Style guide page fix broken link

---

working-on-nebulab/blog.md

This updates the blogpost guidelines by removing the formal proposal/approval process and adding some useful tips for writing.

Update blog guidelines

---

about-us/what-we-do.md

Updates What We Do with a revised list of services.

Update What We Do

---

how-we-work/tracking-time.md

This is rework and translation of #84.
I got my head around the previews content... I simply added a section and I think
this is now super-easy to understand.

Add another section to time tracking

---

personal-growth/benefits.md
personal-growth/conferences.md
processes/travel-policy.md

This is the first version of the travel policy.
We need both English and content review. 
It's still WIP:

Introducing the brand new travel policy

---

README.md

Insert Travel policy link under Processes in the Readme file.

Update readme with the travel policy

---

processes/travel-policy.md

Simplifies and streamlines language and structure.

Streamline Travel policy

---

personal-growth/fridays.md

Update Demo Fridays rhythm and add cal events info

---

processes/paid-time-off-and-overtime.md

Closes #83. Clarifies our policy for the Patron Saint holiday.

Patron Saint policy

---

personal-growth/mentoring-and-1-1.md

Update 1:1s section with new practices

---

useful-resources/privacy-policy.md

Updates the privacy policy by ensuring it only reflects data collection and data management on employees.

Update privacy policy

---

how-we-work/tracking-time.md

New time tracking policy

---

README.md
personal-growth/benefits.md
personal-growth/learning-english.md

English lessons

---

personal-growth/learning-english.md

Update professional coaches section

---

README.md
personal-growth/becoming-a-mentor.md

Closes #82.
Adds some useful content for individual contributors who want to get into the mentoring game.
I think eventually this will become its own section in the playbook, but for the time being it's okay if it's just a single chapter.

Becoming a mentor

---

how-we-work/tracking-time.md

Small changes/rewording of the tracking time page

---

the-offices/music.html.md

Relax restrictions on music genres

---

about-us/our-values.html.md

"Problem owning" has always been quite weird to begin with. Plus, one word is easier to remember.
Closes #138.

Rename Problem Owning value to Ownership

---

how-we-work.html.md
how-we-work/all-hands-meeting.md

Closes #137.
I have not added a link to Tadum because the playbook is public.

All Hands meeting

---

processes/travel-policy.html.md

Add work and travel info

---

personal-growth/fridays.html.md

This PR closes #158 
Adding quantitative details to Fridays section.

Update client work and Friday time section

---

working-on-nebulab/playbook.html.md

Closes #146 by adding an explicit link to the GH repository.

Update Playbook section to link to the repository

---

.github/issue_template.md
.github/pull_request_template.md

Adds an issue template with appropriate todos and adds a todo for configuring any required Netlify redirects when moving content.

Update GH templates

---

how-we-work/meetings.html.md

Closes #153 by documenting the process we use to make and document decisions that are taken during meetings.

Decision-making process

---

working-on-nebulab/blog.html.md

Update Blog section with more info about the process

---

people-ops.html.md
people-ops/performance-plans.html.md

Documents our performance plan process, which is initiated when an employee's performance is unsatisfactory.

Document the Performance Plans process

---

README.md
index.html.md

Adjusts both the readme and the introduction on the playbook itself to make it shorter and more to the point.

Adjust wording in playbook introduction

---

how-we-work/tools.html.md
how-we-work/tracking-time.html.md
how-we-work/where-when-and-how.html.md
people-ops/travel-policy.html.md
personal-growth/becoming-a-mentor.html.md
personal-growth/benefits.html.md
personal-growth/conferences.html.md
personal-growth/fridays.html.md
personal-growth/learning-english.html.md
personal-growth/mentoring-and-1-1.html.md

Fix internal links url

---

client-guide.html.md
client-guide/agile-workflows.html.md

Expands the client guide by adding material on Agile workflows.

Document Agile workflows in the client guide

---

development/using-git-and-github.html.md

The filename for this section was inadvertently renamed to a `.yml` in https://github.com/nebulab/playbook/commit/1fd804a124c88df7a9ac3f08fbb6f9d86413dff5.

Fix filename for Using Git and GitHub

---

client-guide.html.md
client-guide/testing-and-automation.html.md

Documents our approach to software testing in the client guide, clarifying the differences and value of these two practices.

Document our approach to testing in the client guide

---

client-guide/agile-workflows.html.md

Simplifies the Agile workflows section in our Client guide, making it easier to read by removing unnecessary details and remarks and lightening up the tone a bit.

Simplify Agile workflows section in Client guide

---

how-we-work/all-hands-meeting.html.md

This PR improves that All Hands meetings section by explaining why we have this kind of meeting and what we discuss into it. It also simplifies the meeting organization section, but I'm also ok removing it at all.
- ~This change needs a public announcement, _I'll update [the agenda of our monthly meeting](https://tadum.app/rhythms/3JAFLu5H6JKDvLrfzXFZL4nf) once merged_.~
- ~This change moves content around, _I have configured the appropriate [Netlify redirects](https://www.netlify.com/docs/redirects/)._~

Improvements to the All Hands meetings section

---

middleman/assets/stylesheets/components/_heroes.scss

Add a color to the Client Guide section title

---

becoming-a-mentor/running-one-on-ones.html.md
personal-growth/mentoring-and-1-1.html.md

Improves the 1:1 sections (both from the mentor's and the mentee's point of view) with the excellent material @elia put together.

Improve 1:1 tips and resources

---

how-we-work/where-when-and-how.html.md

Fix typo in where-when-and-how

---

middleman/admin/index.html

As requested and suggested by @ShanaRem.

Exclude Google bot from indexing /admin

---

how-we-work/where-when-and-how.html.md

Relax rules on remote work

---

development/using-git-and-github.html.md

Remove unrendered UK flag from Using Git and GitHub

---

working-on-nebulab/blog.html.md

Adds 3 articles I found on the Web about writing and publishing blog posts, which I think cover what we try to do with our blog and some recurring recommendations we give people.

Add blog post writing resources to Blog

---

client-guide.html.md
client-guide/heartbeat-meeting.html.md
client-guide/onboarding.html.md

Create the heartbeat meeting section

---

personal-growth.html.md
personal-growth/competency-matrix.html.md

Adds a chapter on our competency matrix and related processes to the Personal Growth section.

Add Competency Matrix to Personal Growth

---

people-ops.html.md
people-ops/onboarding.html.md
personal-growth/benefits.html.md

Adds an Onboarding chapter to People Ops that explains our onboarding process.

Document our onboarding process

---

working-on-nebulab.html.md
working-on-nebulab/management-scrum.html.md

Adds documentation about our management Scrum processes to Working on Nebulab.

Document management Scrum process

---

client-guide.html.md
client-guide/whats-in-a-rate.html.md

Adds a breakdown of how our rates are calculated to our Client Guide! 👀 💸

Explain our rates in the client guide

---

middleman/assets/stylesheets/base/_typography.scss

This fixes tables "hugging" the paragraph below them.

Add bottom margin to tables

---

how-we-work/all-hands-meeting.html.md
how-we-work/meetings.html.md
how-we-work/tools.html.md
how-we-work/where-when-and-how.html.md

Multiple fixes for the How we work section that improve content formatting and accuracy.

Revamp How we work

---

people-ops/hiring.html.md

Moves some internal hiring guidelines to the public Hiring section.

Add hiring manager guidelines to Hiring

---

leading-teams.html.md
leading-teams/fulfillment-meeting.html.md
mentoring-people.html.md
mentoring-people/mentors-roundtable.html.md

Documents the Fulfillment meeting and Mentors roundtable in their respective section.

Document mentor and team lead quarterly meetings

---

useful-resources/email-signature.html.md

Fix email signature formatting

---

leading-teams.html.md
middleman/assets/images/leading-teams.svg
middleman/assets/stylesheets/components/_heroes.scss

Adds the cover for the Leading teams section.
Closes #264.

Add Leading teams illustration

---

_redirects
our-offices.html.md
our-offices/health-and-safety.html.md

Rename Workplace health and safety to Health and safety

---

middleman/layouts/shared/_head.html.erb

These were requested by @ShanaRem and should improve SEO.

Add canonical URLs

---

middleman/layouts/shared/_head.html.erb

Adjust Open Graph tags

---

.github/pull_request_template.md
working-on-nebulab/blog.html.md

Updates the blog post process and PR checklist to give authors more responsibility over the publication of new blog posts and new playbook pages.

Update publication processes

---

people-ops/benefits.html.md

I'm removing the internet budget because we're not providing this benefit at the moment.

Remove Internet Budget

---

how-we-work.html.md
how-we-work/donut.html.md

Adds information about Donut pairings to the How we work section.

Add Donut to How we work

---

how-we-work/all-hands-meeting.html.md
how-we-work/meetings.html.md
how-we-work/tools.html.md
mentoring-people/running-one-on-ones.html.md

This changes the parts where Soapbox/Whereby are reported and updates
with the latest practices.
Closes #292

Playbook reports some tools we don't use anymore

---

people-ops/hiring.html.md

This reflects on the playbook things that have been updated recently.

Update hiring process

---

people-ops/benefits.html.md

Update the Macbook specs for the hire kit

---

personal-growth/learning-english.html.md

Add English level assessment paragraph

---

people-ops/hiring.html.md

Updates the description of the Technical Assessment step in the hiring process.

Update Technical Assessment step description

---

people-ops/hiring.html.md

Fixes a small grammar error in the hiring section.

Fix grammar glitch in hiring section

---

leading-teams/discovery-and-estimation.html.md

Fix typo in discovery-and-estimation

---

personal-growth/conferences.html.md

Just fixes a sentence not completed.

Fix a sentence in Conferences page

---

how-we-work/tracking-time.html.md

Update time tracking internal projects

---

personal-growth/mentoring-and-one-on-ones.html.md

Update frequency and duration for 1:1s

---

personal-growth/competency-matrix.html.md

Competency Matrix updates

---

useful-resources/email-signature.html.md

Update email signature

---

source/personal-growth/conferences.html.md

We are participating in virtual events due to the pandemic, and we don't have to travel anymore to reach a conf venue; so the money budget decreased accordingly.
Also, I took the chance to add:
- a principle on how conference days should be counted and if we should work or not on those days;
- how to report conference days on Factorial.

Update conference budget 2021

---

source/people-ops/travel-policy.html.md

Fixed a grammar issue wherein the correct sentence should be `If you miss **yours** because of...` instead of `If you miss **your** because of...`

fix: grammar issue in travel paragraph

---

source/personal-growth/competency-matrix.html.md

Introducing mid-level promotions

---

source/people-ops/paid-time-off.html.md

We're not using rounding-offs anymore.

Remove rounding-offs

---

source/people-ops/hiring.html.md

Updates our hiring process according to the latest updates we've made.

Update hiring process as per new policies

---

source/people-ops/paid-time-off.html.md

Change the sick leave document to an english one

---

source/people-ops/benefits.html.md

I've also renamed stipend to budget because that's what we use everywhere.

Sort benefits to reflect what is on nebulab.com

---

source/how-we-work.html.md
source/how-we-work/tracking-time.html.md
source/how-we-work/where-when-and-how.html.md

We were using some pretty old stuff which doesn't make sense anymore.
This relaxes the requirements and updates them with the latest
practices.

Update flexible scheduling text

---

source/people-ops/onboarding.html.md

Not much, just what the title says.

Update Onboarding page with latest donut process

---

source/people-ops/hiring.html.md
source/personal-growth.html.md
source/personal-growth/apprenticeship-program.html.md

Adds a new chapter about the Apprenticeship Program to Personal Growth, and updates the Hiring chapter to reference the program.

Apprenticeship Program

---

source/people-ops/benefits.html.md

This PR changes Nebulab Hire Kit, by updating MacBook Pro models with new ones, and removing corporate credit card.

Update Hire kit

---

source/personal-growth.html.md
source/personal-growth/learning-library.html.md

Adds a chapter about our Learning Library to the Personal Growth section.

Write playbook chapter about the Learning Library

---

source/people-ops/hiring.html.md

We rarely made the initial screen in 15 minutes so it's worth updating saying it will probably take longer.

Update Initial screen duration

---

source/managing-teams/matrix-evaluations.html.md
source/people-ops/compensation.html.md
source/personal-growth/competency-matrix.html.md

Updates a few paragraphs to clarify the process behind post-promotion salary adjustments.

Clarify process for post-promotion salary adjustments

---

source/people-ops/hiring.html.md

Corrected some typos that were found on the page.

Corrected some typos

---

source/internal-projects/nebulab.html.md

The leadership role was updated from "directors" to "managing partners".

Update the new leadership role

---

source/people-ops/parting-ways.html.md

The #general channel was mentioned but in reality, the #announcements channel is the right one for these types of update.

Updated to the right slack channel on Resignation

---

source/personal-growth/investment-time.html.md

There was a typo: "cold" instead of "could".

Typo on word

---

source/personal-growth/coaching-and-one-on-ones.html.md

Adding Lattice as a new reference for 1:1s meeting agendas.

Adding Lattice for 1:1s meeting notes

---

source/company-rituals/all-hands-sessions.html.md

The page only mentioned the directors which are the Managing Partners, so I added both roles now.

Adding the MP role to the page
