nebulab/playbook

- .github/pull_request_template.md
The main reason behind adding this template is providing a well-defined process to be sure all relevant changes we'll make to our Playbook will be notified to the rest of the team. This will be made in our new monthly meeting.
This change has already been added to the [mentioned document]([the agenda of our monthly meeting](https://docs.google.com/document/d/1hjSS-o_cKs5Db1E1TqRykfQfnAQUFS4gDXMQ2x-CSzE/edit?usp=sharing)). :trollface:
> Add a basic PR template

- personal-growth/fridays.md
We have decided to simplify our Friday time policy in order to ensure everyone is working on projects that are value to both them and the company.
> Simplify Friday time policy

- .github/pull_request_template.md
We moved the meeting agenda from Google Docs to a Tadum Meeting accessible to everyone in Nebulab.
> Update All Hands Agenda link

- processes/travel-policy.md
The available days to attend a conference are to be considered as **working** days spent at the conf.
Introducing the new part-time contract limit.
> Clarification about conference budget

- README.md
- index.html.md
Now that the website is live, we can remove the table of contents from the readme and simply link people to the live site.
> Remove ToC from readme

- useful-resources/press-kit.html.md
Ref to #167
_Press Kit_ was previously a direct link to Google Drive folder; but we miss it after the Playbook restyle, because now, all the topics links to their own md file.
So, in this commit I created the missing `Press Kit.md`
> Add Press Kit as a topic

- middleman/assets/stylesheets/base/_grid.scss
- middleman/assets/stylesheets/base/_variables.scss
- middleman/assets/stylesheets/components/_navigation.scss
Ref. to #177 and #178 
Now the logo is clickable overall and the default color of the sidebar items is the gray `#898989` that become black `#222` on hover or when the item is `opened`
> Fix on logo and on the default sidebar links color

- middleman/assets/stylesheets/base/_grid.scss
- middleman/assets/stylesheets/base/_variables.scss
- middleman/layouts/shared/_header.html.erb
- middleman/layouts/shared/_sidebar.html.erb
The width of the paragraphs container (home page) has been enlarged: from `40%` to `55%`
I also move the menu toggle button outside the `header`: this caused unexpected behavior when the menu was visible on mobile.
> Adjust the width of paragraphs container on home

- development/job_offers.yml
This updates the link to trunk based development.
The old link was referring to the GitHub Flow which is similar... but different from what we do.
> Update trunk based development link

- development/using-git-and-github.html.md
It is actually linking to the post on the line above.
> Fix a commit message link in using git page

- middleman/helpers/title_tag_content_helper.rb
- middleman/layouts/playbook/chapter.erb
- middleman/layouts/shared/_head.html.erb
- middleman/lib/playbook/chapter.rb
Fixes #209. From the issue description:
The title tags are too short and not clear about the content of the page. We need to create this kind of structure:
_section name - chapter name | The Nebulab playbook_
e.g., **Personal growth - Becoming a mentor | The Nebulab playbook**
> Optimize title tags

- working-on-nebulab/playbook.html.md
Adding a Netlify CMS guide so to help content creators with its usage.
> Create Netlify CMS guide

- people-ops/hiring.html.md
We have never actually implemented this practice and no candidate has asked for it. We hope to make it a part of the hiring process once the benefits and structure are clearer.
> Remove payment for failed technical assessments

- development/style-guide.html.md
- people-ops/travel-policy.html.md
Unless it's commonly used (but unknown to me), "Fry" is not the correct short name for "Friday".
Url mismatches are self explanatory.
> Fixes a typo on the short name for a day, fixes some url mismatches

- leading-teams.html.md
- leading-teams/visiting-clients.html.md
This has been in our internal private playbook for far too long.
There's no reason it shouldn't be shared with the world, since it's also useful for clients who host us!
> Add client trip process and tips to Leading teams

- middleman/Gemfile.lock
- middleman/assets/images/search.svg
- middleman/assets/stylesheets/base/_grid.scss
- middleman/assets/stylesheets/components/_algolia-search.scss
- middleman/assets/stylesheets/components/_navigation.scss
- middleman/assets/stylesheets/playbook-style.css.scss
- middleman/layouts/shared/_all_js.html.erb
- middleman/layouts/shared/_head.html.erb
- middleman/layouts/shared/_navigation.html.erb
- middleman/layouts/shared/_sidebar.html.erb
This PR adds search to our Playbook, via [Algolia Docsearch](https://community.algolia.com/docsearch/).
**TL;DR**: DocSearch is built in two parts:
– a crawler which we run on their own infrastructure every 24 hours. It follows every link in the Nebulab website and extracts content from every page it traverses. It then pushes this content to an Algolia index.
– a JavaScript snippet to be inserted in our website, which is what this PR does.
- ~[ ] This change moves content around and I have configured the appropriate [Netlify redirects](https://www.netlify.com/docs/redirects/)._~
> Add basic code to make algolia docsearch work

- _redirects
- how-we-work/where-when-and-how.html.md
- mentoring-people/promoting-growth.html.md
- personal-growth.html.md
- personal-growth/benefits.html.md
- personal-growth/investment-fridays.html.md
- personal-growth/mentoring-and-one-on-ones.html.md
We are in the process of refocusing our Friday efforts by ensuring our work has a tangible return on ourselves and the company.
As part of this approach, we took inspiration from [thoughtbot](https://thoughtbot.com/blog/investment-time) and are renaming Fridays to Investment Fridays.
> Rename Fridays to Investment Fridays

- personal-growth/competency-matrix.html.md
Upon further research, we came to realize that 360 feedback is not a good way to inform promotion decisions, because employees are not trained enough to provide accurate feedback.
For the time being, we're reverting to a more traditional top-down model, but may re-evaluate it in the future after experimentation.
> Remove 360 reviews from the promotion process

- leading-teams.html.md
- leading-teams/what-team-leads-do.html.md
- mentoring-people/what-mentors-do.html.md
Currently, the difference between mentors and team leads is not entirely clear, and some information was outdated (e.g. mentors don't handle client projects anymore).
This is an attempt at providing a good explanation of their different responsibilities.
> Distinguish between Mentors and Team Leads more clearly

- _redirects
- development.html.md
- development/working-with-ruby-on-rails.html.md
Updates the title of the "Working with Rails" page for better SEO.
Closes #235.
> Use 'Ruby on Rails' instead of 'Rails' for SEO

- .github/pull_request_template.md
Requires authors of new pages to get a meta description from @ShanaRem before merging their PR.
> Require meta description in PR template checklist

- how-we-work/tools.html.md
Moz found a broken link in the Tools chapter to the Time off and overtime chapter.
> Fix broken link to Time off and overtime

- leading-teams/what-team-leads-do.html.md
- people-ops/onboarding.html.md
- personal-growth/competency-matrix.html.md
- working-on-nebulab/management-scrum.html.md
Search engines usually truncate descriptions after 160 characters, and we definitely don't want that.
> Shorten meta descriptions longer than 160 characters

- middleman/assets/javascripts/chapter.js
- middleman/assets/stylesheets/components/_local-anchor.scss
- middleman/assets/stylesheets/playbook-style.css.scss
- middleman/layouts/playbook/chapter.erb
Fixes #208. It adds anchor links to contents titles so to allow users to  share links related to specific contents of the Playbook. Here a screenshot of the result:
@mfrecchiami and @davidedistefano please have a look ;)
> Add anchor links to contents titles

- personal-growth/investment-fridays.html.md
This is in contrast with our previous policy that required developers to sacrifice their Friday if they took time off for some reason.
> Maintain investment time after taking time off

- people-ops/travel-policy.html.md
- personal-growth/conferences.html.md
Updates our 2020 conference budget and policy for speaking engagements.
Also moved some content from the Travel policy to the Conferences page, which was a more appropriate location.
> Update conference budget and policy for 2020

- people-ops/benefits.html.md
Adds information about our learning stipend to the Benefits section. This has always been in place, we just forgot to include it in the playbook.
Fixes #285.
> Add learning stipend to Benefits

- people-ops/benefits.html.md
- people-ops/travel-policy.html.md
In base alle indicazioni raccolte lo scorso anno al ritorno dai viaggi, con l'aiuto di Andrea, abbiamo migliorato il testo della travel policy, fornendo una nuova versione per il 2020.
> Add more details to the travel policy

- people-ops/time-off-and-overtime.html.md
There was a piece of missing but useful information about how much time Nebulab can keep accrued days that a team member can spend as vacation time.
> Add info about expiration of accrued vacation days

- leading-teams.html.md
- leading-teams/leadership-principles.html.md
Adds a Leadership principles chapter to the Leading teams section, with some useful information and tips on leading teams.
> Add Leadership principles to Leading teams

- _redirects
To make it easier to share links to the playbook each section should be
redirected to the first chapter.
This adds the Netlify redirects needed for this.
Closes #205
> Add Netlify redirects from sections to chapter

- how-we-work/donut.html.md
This PR updates the Donut policy:
- it's now bi-weekly;
- it pairs 3 people;
- it should last between 10-20 minutes;
- it should not be tracked on Harvest.
> Update Donut to bi-weekly

- how-we-work/donut.html.md
- how-we-work/where-when-and-how.html.md
Ref. to #300 
I've found only two missed Italian names of Slack channels 🙂
> Update two missed channels name to new EN name

- how-we-work/tracking-time.html.md
The "Time wasting" project's use on Harvest was deprecated some time ago.
> Remove "Time wasting" project use

- working-on-nebulab/blog.html.md
Adds a new step to blog post publication process: creating a card on our social media board to allow to review and schedule for publication social media content.
- ~~[ ] This change moves content around and I have configured the appropriate [Netlify redirects](https://www.netlify.com/docs/redirects/).~~
- ~~[ ] This change adds a new page and I have written an appropriate meta description.~~
> Add social media to blog publication process

- leading-teams.html.md
- leading-teams/discovery-and-estimation.html.md
Adds a new chapter explaining our project discovery and estimation process. Useful both for clients and team members.
> Add Discovery and Estimation to Leading teams

- people-ops.html.md
- people-ops/international-compensation.html.md
We're hiring people outside of Italy. Introducing an international compensation policy, we should be able to offer the right salary to candidates.
> Add the international compensation policy

- people-ops/parting-ways.html.md
- people-ops/payroll.html.md
- people-ops/time-off-and-overtime.html.md
Our team is internationally distributed, and the People operations chapter was outdated. This PR aims to solve this inconsistency, offering the same treatment to every team member, as far as the local bureaucracy lets us do it.
> Make people ops chapter consistent with international hire

- personal-growth/competency-matrix.html.md
We are now using [Progression](https://progressionapp.com) for matrix evaluations. This PR updates the Competency Matrix page to reflect the new process and link to the new public matrix on Progression.
> Update Competency Matrix with notes on Progression

- about-us/mission.html.md
- about-us/values.html.md
- about-us/what-we-do.html.md
- client-guide/agile-workflows.html.md
- how-we-work/all-hands-meeting.html.md
- how-we-work/donut.html.md
- how-we-work/meetings.html.md
- index.html.md
- mentoring-people/what-mentors-do.html.md
@Azeem838 picked up a typo a few weeks ago and I also thought I'd use this opportunity to test what Grammarly could suggest on a couple of pages while I was making the fix. 
There is a really cool VS Code [extension](https://github.com/znck/grammarly) which is actually an unofficial Grammarly client. This makes writing well-edited markdown so much easier.
Result of the test: Even though it can't be blindly followed, Grammarly could be pretty useful for the Playbook and Solidus documentation if there is ever some time to go through the tedious process of editing 😆.
> Fix typos, grammar and increase clarity while giving Grammarly a test run

- .github/workflows/cache.yml
The playbook is still served by CloudFlare so everytime something
changes we need to invalidate the nebulab.com cache.
> Invalidate CloudFlare cache on updates

- source/people-ops/benefits.html.md
I've updated the hire-kit content with the latest version of products, and I've also taken the chance to change all the pages we were linking to from Italian to English versions.
> Update the hire-kit and link products to EN pages

- source/useful-resources/email-signature.html.md
We can't recall the reason why we added that information. Doesn't look important anymore.
> Remove phone number from suggested email signature

- source/people-ops/benefits.html.md
Assuming this page will be visited a lot for hiring purposes... I think
we should link to the previous TR.
In addition to providing a benefits page with more information we have
the benefit of streamlining the job post pages that currently link the
TR material.
> Link to past team retreat in the benefits page

- source/people-ops/benefits.html.md
The main reasoning about this is so that we can use them on our job
posts.
> Update and rewrite a few benefits

- source/people-ops/benefits.html.md
`regular PTO` links to `/work-fundamentals/distributed-work/` which has nothing to do with PTOs.
> Remove PTO link to nowhere

- source/people-ops/benefits.html.md
I have the feeling that our 22 days of PTO wording is not clear enough for people from all countries and for someone who reads through it in a hurry. It is important that everybody understands right away the the sum of our calculation adds up to 35 days of PTO. Therefor we should start with that number.
> Improves the how many days of PTO section.

- source/people-ops/hiring.html.md
The section which describes "Technical test" in `hiring.md` mentions the aptitude test in the last sentence instead of the technical test. This is most likely a typo. This PR fixes that issues.
~~- [ ] This changes the content index and I've made sure `_redirects` are updated.~~
> Fix copy/paste typo in hiring.md

- source/people-ops/benefits.html.md
There's no official sleeve available for the new macs yet and we decided that in general, the sleeve is pretty useless.
> Remove laptop sleeve from benefits

- source/people-ops/hiring.html.md
Removes all references to HackerRank from the playbook, and updates the language around the technical test to make it a bit more generic (so that we can reuse it for non-technical positions).
> Remove HackerRank from the hiring process

- source/managing-teams/holding-one-on-ones.html.md
Update from "Fellow" to "Lattice" as the main platform for 1:1s meeting notes.
> Update platform for 1:1s notes
